"""Build results/results.md and results/failures.md from the run JSON. Never edit those files by hand.

    python -m loop.report
    python -m loop.report --runs .dryrun/runs --out .dryrun     # against dry runs, for testing

Uses the latest run per cell. The ten-line summary is written by a person (or the agent) into
results/summary.md after reading the tables, and is copied in verbatim.
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path

from config import RESOLUTIONS, RESULTS_DIR, ROOT, RUNS_DIR, SEEDS, TOLERANCE
from loop.models import MODELS, spent_usd
from scene.sim import ERRORS


def load_runs(runs_dir: Path) -> list[dict]:
    latest = {}
    for path in sorted(runs_dir.glob("*/*/run.json")):  # timestamps sort, so the last one wins
        run = json.loads(path.read_text())
        latest[run["cell"]] = run
    return list(latest.values())


def frac(runs: list[dict], key) -> str:
    vals = [key(r) for r in runs]
    vals = [v for v in vals if v is not None]
    return f"{sum(vals)}" + ("" if len(vals) == len(SEEDS) else f" (of {len(vals)})") if vals else ""


def matrix_table(runs: list[dict], condition: str) -> list[str]:
    by = defaultdict(list)
    for r in runs:
        if r["condition"] == condition and r["error"] in ERRORS:
            by[(r["model"], r["resolution"], r["error"])].append(r)
    if not by:
        return []
    fixed_col = condition == "with_text"
    head = "| Model | Resolution | Error | Named correctly (of 3) |" + (" Fixed within 5% (of 3) |" if fixed_col else "")
    lines = [head + " Tokens per run |", "|" + "---|" * (head.count("|"))]
    models = sorted({k[0] for k in by}, key=lambda m: list(MODELS).index(m))
    for m in models:
        for err in ERRORS:
            for res in RESOLUTIONS:
                rs = by.get((m, res, err), [])
                if not rs:
                    continue
                tokens = round(sum(r["tokens"]["total"] for r in rs) / len(rs))
                row = f"| {MODELS[m].label} | {res} | {ERRORS[err].label} | {frac(rs, lambda r: r['readback']['named_correctly'])} |"
                if fixed_col:
                    row += f" {frac(rs, lambda r: r['fixed_within_tolerance'])} |"
                lines.append(row + f" {tokens:,} |")
    return lines


def lowest_closing_resolution(runs: list[dict], model: str, condition: str) -> str:
    """The number that matters: the lowest resolution where naming is 3 of 3 for all three errors."""
    ok = []
    for res in RESOLUTIONS:
        cell_ok = []
        for err in ERRORS:
            rs = [r for r in runs if r["model"] == model and r["condition"] == condition
                  and r["resolution"] == res and r["error"] == err]
            cell_ok.append(len(rs) == len(SEEDS) and all(r["readback"]["named_correctly"] for r in rs))
        if all(cell_ok):
            ok.append(res)
    complete = all(any(r["model"] == model and r["condition"] == condition and r["resolution"] == res
                       and r["error"] == err for r in runs) for res in RESOLUTIONS for err in ERRORS)
    if not complete:
        return "incomplete"
    return f"{min(ok)} px" if ok else "none (did not close at any resolution tested)"


def controls(runs: list[dict]) -> list[str]:
    lines = ["| Model | Control | Resolution | Named | Correct | Fixed / unchanged | Tokens |", "|---|---|---|---|---|---|---|"]
    rows = [r for r in runs if r["error"] == "none" or (r["condition"] == "image_only" and r["resolution"] == 64
                                                        and r["error"] == "hoop_low" and r["seed"] == 0)]
    for r in sorted(rows, key=lambda r: (list(MODELS).index(r["model"]), r["condition"], -r["resolution"])):
        what = "Unmodified scene" if r["error"] == "none" else "Hoop too low, scene text withheld"
        fixed = "n/a" if r["fixed_within_tolerance"] is None else r["fixed_within_tolerance"]
        lines.append(f"| {MODELS[r['model']].label} | {what} | {r['resolution']} | {r['readback']['named']} | "
                     f"{r['readback']['named_correctly']} | {fixed} | {r['tokens']['total']:,} |")
    return lines if len(lines) > 2 else []


def failures(runs: list[dict]) -> str:
    out = ["# What the model said when it was wrong", "",
           "Generated by `python -m loop.report` from results/runs. One entry per run that named the wrong object "
           "or whose correction did not land within tolerance.", ""]
    bad = [r for r in runs if not r["readback"]["named_correctly"] or r["fixed_within_tolerance"] is False]
    for r in sorted(bad, key=lambda r: r["cell"]):
        p = r["readback"]["parsed"] or {}
        out += [f"## {r['cell']}", "",
                f"- Expected `{r['expected_mismatch']}`, named `{r['readback']['named']}`"
                + (f" (parse error: {r['readback']['parse_error']})" if r["readback"]["parse_error"] else ""),
                f"- What it said was wrong: {p.get('what_is_wrong', '')!r}",
                f"- What it saw: {p.get('description', '')!r}",
                f"- Evidence it claimed: {p.get('evidence', '')}"]
        c = r.get("correction")
        if c:
            if not c["loaded"]:
                out.append(f"- Correction did not load: {c['load_error']}")
            else:
                m = r["measurements"]["corrected"]
                out.append("- After correction: " + ", ".join(f"{k} {m[k]:.3f}" for k in r["targets"]))
            if c.get("diff_vs_injected"):
                out += ["", "```diff", c["diff_vs_injected"].rstrip(), "```"]
        out += [f"- Run: `{r['run_dir']}`", ""]
    if not bad:
        out.append("No failures recorded yet.")
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--runs", type=Path, default=RUNS_DIR)
    ap.add_argument("--out", type=Path, default=RESULTS_DIR)
    args = ap.parse_args()
    runs = load_runs(args.runs)
    real = [r for r in runs if not r["dry_run"]]
    if args.runs.resolve() == RUNS_DIR.resolve():
        runs = real  # dry runs never reach the real results
    models = sorted({r["model"] for r in runs}, key=lambda m: list(MODELS).index(m))

    summary_file = args.out / "summary.md"
    md = ["# Experiment 1 results: round trip", "",
          "Generated by `python -m loop.report` from the run JSON in `results/runs/`. Do not edit by hand.", ""]
    if any(r["dry_run"] for r in runs):
        md += ["**DRY RUN: scripted replies, no model was called. These numbers mean nothing.**", ""]
    md += ["## Summary", "", summary_file.read_text().strip() if summary_file.exists() else "_Not written yet._", ""]
    md += ["## The number that matters", "",
           "Lowest readback resolution at which the model named the wrong object 3 of 3 times for all three errors.", ""]
    for m in models:
        line = f"- {MODELS[m].label}, with scene text: {lowest_closing_resolution(runs, m, 'with_text')}"
        if any(r["model"] == m and r["condition"] == "image_only" and r["error"] != "none" and
               not (r["resolution"] == 64 and r["error"] == "hoop_low" and r["seed"] == 0) for r in runs):
            line += f"; image only: {lowest_closing_resolution(runs, m, 'image_only')}"
        md.append(line)
    if not models:
        md.append("- No runs yet.")
    md += ["", "## Matrix (scene text given)", "",
           f"Named: the model's `mismatch` equals the object the error was put in. Fixed: after one correction turn, the "
           f"measured quantity is within {TOLERANCE:.0%} of the brief, read from MuJoCo state.", ""]
    md += matrix_table(runs, "with_text") or ["_No runs yet._"]
    md += ["", "## Controls", ""] + (controls(runs) or ["_No runs yet._"])
    img = matrix_table(runs, "image_only")
    if len([r for r in runs if r["condition"] == "image_only"]) > len(models):
        md += ["", "## Image-only arm (scene text withheld)", ""] + img
    md += ["", "## Spend", "", f"Ledger total: ${spent_usd():.2f}. Runs counted here: {len(runs)}.", ""]
    md += ["## Runs", ""] + [f"- `{r['cell']}`: `{r['run_dir']}`" for r in sorted(runs, key=lambda r: r["cell"])]

    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "results.md").write_text("\n".join(md) + "\n")
    (args.out / "failures.md").write_text(failures(runs))
    print(f"{len(runs)} runs -> {args.out / 'results.md'}, {args.out / 'failures.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
