"""Compile the seven briefs from the typed vocabulary, judge each with 1d's tests, then write each of 1d's five
breaks in the vocabulary and show what the compiler and the readback say. No model calls, no spend.

    python -m typed.demo            # writes typed/demo_output.md
"""

from __future__ import annotations

import dataclasses
from pathlib import Path

from harder import tests
from typed import briefs as B
from typed.compiler import compile_world, render
from typed.parts import Hinge, OpenBox, Pusher
from typed.replay import replay
from typed.units import Nm_per_rad, Nms_per_rad, deg, m3, mps, rad, v3

OUT = Path(__file__).with_name("demo_output.md")


def judged(name: str, world) -> tuple[str, list[str]]:
    c = compile_world(world)
    if c.problems:
        return "does not compile", [render(c.problems)]
    j = tests.judge(name, c.xml)
    verdict = "passes its 1d test" if j.get("passed") else "fails its 1d test: " + ", ".join(
        k for k, v in j["checks"].items() if not v)
    return verdict, replay(c).events()


def swap(world, kind, **changes):
    return dataclasses.replace(world, parts=[dataclasses.replace(p, **changes) if isinstance(p, kind) else p
                                             for p in world.parts])


def door_with(range_, opened):
    w = B.door()
    d = w.parts[1]
    h = Hinge("z", range=range_, stiffness=Nm_per_rad(40), rest=deg(0), damping=Nms_per_rad(25))
    return dataclasses.replace(w, parts=[w.parts[0], dataclasses.replace(d, hinge=h, opened=opened)])


def main() -> None:
    lines = ["# The seven briefs in the typed vocabulary", "",
             "Generated by `python -m typed.demo`. Each world is compiled from `typed/briefs.py`, run in MuJoCo and "
             "judged by 1d's own tests (`harder/tests.py`). The readback is `typed/replay.py`'s events, in the "
             "vocabulary's own names.", ""]
    for name, fn in B.BRIEFS.items():
        verdict, ev = judged(name, fn())
        lines += [f"## {name}: {verdict}", "", "```", *ev, "```", ""]

    lines += ["# 1d's five breaks, written in the vocabulary", ""]
    cat = B.catapult()
    arm = cat.parts[1]
    weak = dataclasses.replace(arm, hinge=dataclasses.replace(arm.hinge, stiffness=Nm_per_rad(2.0)))
    cases = [
        ("door", "the 1d break as written in MJCF: range (0, 2.1) with no unit",
         door_with((deg(0), 2.1), rad(1.2))),
        ("door", "the same slip with a unit attached, deg(2.1)",
         door_with((deg(0), deg(2.1)), rad(1.2))),
        ("door", "what the author meant, rad(2.1)",
         door_with((rad(0), rad(2.1)), rad(1.2))),
        ("cup", "the cup moved from x = 2.05 to 2.65 m",
         swap(B.cup(), OpenBox, at=m3(2.65, 0, 0))),
        ("stack", "the pusher at 1.5 m/s instead of 3.0",
         swap(B.stack(), Pusher, velocity=v3(mps(1.5), mps(0), mps(0)))),
        ("catapult", "the spring's stiffness 2.0 instead of 3.0",
         dataclasses.replace(cat, parts=[cat.parts[0], weak, *cat.parts[2:]])),
    ]
    for name, what, world in cases:
        verdict, ev = judged(name, world)
        lines += [f"## {name}, {what}: {verdict}", "", "```", *ev, "```", ""]
    lines += ["## shot, backspin added to the launch", "",
              "Not expressible: `Ball` has a `launch` velocity and no spin field, so this break cannot be written. "
              "That is a choice of vocabulary, and it also means a deliberate spin cannot be written.", ""]
    OUT.write_text("\n".join(lines))
    print(OUT.read_text())


if __name__ == "__main__":
    main()
