"""The world language, end to end: parse each .world file in typed/worlds/, compile it, judge it with 1d's tests,
check its `expect` lines against the replay, then show what the language says about a few mistakes.
No model calls, no spend.

    python -m typed.lang_demo       # writes typed/lang_output.md
"""

from __future__ import annotations

from pathlib import Path

from harder import tests
from typed.compiler import compile_world, render
from typed.lang import expectations, parse
from typed.replay import replay

HERE = Path(__file__).parent
OUT = HERE / "lang_output.md"


def run(name: str, text: str) -> list[str]:
    prog = parse(text)
    if prog.problems:
        return ["```", render(prog.problems), "```"]
    c = compile_world(prog.world)
    if c.problems:
        return ["```", render(c.problems), "```"]
    j = tests.judge(name, c.xml)
    verdict = "passes its 1d test" if j["passed"] else "fails its 1d test: " + ", ".join(
        k for k, v in j["checks"].items() if not v)
    out = [f"MuJoCo: {verdict}.", ""]
    for line, ok, evidence in expectations(prog, replay(c).events()):
        out.append(f"- {'✓' if ok else '✗'} `{line}`: {evidence}")
    return out


def edit(name: str, old: str, new: str) -> str:
    text = (HERE / "worlds" / f"{name}.world").read_text()
    assert old in text, (name, old)
    return text.replace(old, new)


MISTAKES = [
    ("door", "1d's door break: the range's end written with no unit", "from 0° to 120°", "from 0° to 2.1"),
    ("door", "the same slip, in degrees", "from 0° to 120°", "from 0° to 2.1°"),
    ("pendulum", "a mass where a length goes", "length             95 cm", "length             95 g"),
    ("pendulum", "a misspelt line", "hangs from", "hangs frum"),
    ("cup", "a misspelt part name", "stands  on floor, 2.05 m along", "stands  on floor, 1 m beyond bal"),
    ("catapult", "1d's catapult break: the spring at 2 N·m/rad instead of 3", "spring   3 N·m/rad", "spring   2 N·m/rad"),
    ("cup", "1d's cup break: the cup 60 cm further away", "2.05 m along", "2.65 m along"),
]


def main() -> None:
    lines = ["# The seven briefs in the world language", "",
             "Generated by `python -m typed.lang_demo`. Each file in `typed/worlds/` is parsed into the typed parts, "
             "compiled, run in MuJoCo and judged by 1d's own tests. Its `expect` lines are checked against the "
             "replay's events.", ""]
    for f in sorted((HERE / "worlds").glob("*.world")):
        lines += [f"## {f.stem}", "", "```", f.read_text().rstrip(), "```", "", *run(f.stem, f.read_text()), ""]
    lines += ["# Mistakes, and what the language says", ""]
    for name, what, old, new in MISTAKES:
        lines += [f"## {name}: {what}", "", f"`{old.strip()}` becomes `{new.strip()}`", "",
                  *run(name, edit(name, old, new)), ""]
    OUT.write_text("\n".join(lines))
    print(OUT.read_text())


if __name__ == "__main__":
    main()
