"""Could a debugger that tries forks have found a fix the builder missed? ($0, no model calls)

    python -m debug.bench                  # every revision of the 1j to 1l long worlds with a run in words
    python -m debug.bench --report         # debug/results/bench.md from bench.json

For every file a builder wrote, saw fail and then revised (ladder/results_breaks/breaks.json), this asks the debugger's
fork tool (debug/tools.py) about the first broken link and compares with what the builder's own revision did:

- builder: did their next file move the first break forward without losing a link that held?
- forks: did any single-number change on the lines behind that link do so?
- brief numbers: how many of those clean forks change a number the brief itself states (a size, an angle, a gap),
  which a faithful builder should not change. A fork existing is an upper bound on what an agent with the tool
  could do, not a result: the agent still has to choose, and to stay true to the brief.
"""

from __future__ import annotations

import json
import re
import sys
import time
from pathlib import Path

from debug.tools import Session
from typed.lang import LIBRARY

HERE = Path(__file__).parent
OUT = HERE / "results"
BREAKS = HERE.parent / "ladder" / "results_breaks" / "breaks.json"


def first_break(held: list[bool]) -> int:
    return next((i for i, x in enumerate(held) if not x), len(held))


def brief_numbers(text: str) -> set[float]:
    return {abs(float(x)) for x in re.findall(r"-?\d+(?:\.\d+)?", text)}


def is_brief_number(old: str, briefs: set[float]) -> bool:
    v = abs(float(old))
    # as written, in cm, or doubled (MuJoCo boxes take half-sizes); approximate, so it can over- or under-count
    return any(abs(c - b) < 1e-6 * max(1, b) for b in briefs for c in (v, v * 100, v * 2))


def source_of(run_dir: Path, label: str, arm: str) -> tuple[str, str, str | None]:
    if arm == "language":
        src = (run_dir / f"{label}.world").read_text()
        parts = run_dir / f"{label}.parts"
        lib = LIBRARY.read_text()
        if parts.exists():
            lib = lib.rstrip() + "\n\n\n" + parts.read_text()
        return src, "world", lib
    return (run_dir / f"{label}.xml").read_text(), "xml", None


def main() -> int:
    if "--report" in sys.argv:
        return report()
    OUT.mkdir(parents=True, exist_ok=True)
    out_file = OUT / "bench.json"
    done = json.loads(out_file.read_text()) if out_file.exists() else []
    seen = {(d["world"], d["label"]) for d in done}
    for r in json.loads(BREAKS.read_text()):
        if r["arm"] == "blind":
            continue
        rec = json.loads((Path(r["dir"]) / "world.json").read_text())
        briefs = brief_numbers(rec["brief_text"])
        for p, q in zip(r["files"], r["files"][1:]):
            fp = first_break(p["held"])
            if fp == len(r["test"]) or (r["world"], p["label"]) in seen:
                continue
            fq = first_break(q["held"])
            builder_clean = fq > fp and not any(not q["held"][i] for i in range(fp))
            t0 = time.monotonic()
            src, fmt, lib = source_of(Path(r["dir"]), p["label"], r["arm"])
            s = Session(src, fmt, r["test"], rec["sim_seconds"], lib)
            if s.state is None or s.state["first"] != fp:
                row = {"skipped": "did not reproduce"}
            else:
                forks = s.fork_results(fp)
                clean = [f for f in forks if f.get("clean")]
                row = {"forks": len(forks), "clean": len(clean),
                       "clean_not_brief": sum(not is_brief_number(f["old"], briefs) for f in clean),
                       "best_moved": max((f["moved"] for f in clean), default=0), "examples": clean[:5]}
            row |= {"world": r["world"], "exp": r["exp"], "arm": r["arm"], "steps": r["steps"], "label": p["label"],
                    "next": q["label"], "first": fp, "link": r["test"][fp] if fp < len(r["test"]) else None,
                    "builder_clean": builder_clean, "builder_moved": fq - fp, "seconds": round(time.monotonic() - t0, 1)}
            done.append(row)
            out_file.write_text(json.dumps(done, indent=1) + "\n")
            print(r["world"], p["label"], "builder", builder_clean, "forks clean", row.get("clean"), row.get("clean_not_brief"),
                  f"{row['seconds']} s", flush=True)
    return report()


def report() -> int:
    rows = [r for r in json.loads((OUT / "bench.json").read_text()) if "skipped" not in r]
    skipped = sum("skipped" in r for r in json.loads((OUT / "bench.json").read_text()))
    pct = lambda n, d: f"{n} of {d} ({100 * n / d:.0f}%)" if d else "none"
    lines = ["# Could forks have found the fix? (1j to 1l long worlds, $0)", "",
             "Generated by `python -m debug.bench --report`; never edited by hand. Each row: a file a builder saw fail and "
             "then revised. \"Clean\" means the first broken link moved forward and no link that held before was lost. "
             "Forks change one number on the lines behind the first broken link to 1.1, 0.9, 1.5 or 0.5 times itself "
             "(up to 15 numbers, movers first) and judge the whole chain.", "",
             "| Arm | Steps | Revisions | Builder's revision was clean | Some fork was clean | ...changing a number the brief doesn't state | Builder missed, fork found (not a brief number) |",
             "|---|---|---|---|---|---|---|"]
    for arm in ("xml", "language"):
        for steps in (8, 16, None):
            g = [r for r in rows if r["arm"] == arm and (steps is None or r["steps"] == steps)]
            if not g:
                continue
            b = sum(r["builder_clean"] for r in g)
            f = sum(r["clean"] > 0 for r in g)
            fn = sum(r["clean_not_brief"] > 0 for r in g)
            miss = sum((not r["builder_clean"]) and r["clean_not_brief"] > 0 for r in g)
            lines.append(f"| {arm} | {steps or 'all'} | {len(g)} | {pct(b, len(g))} | {pct(f, len(g))} | {pct(fn, len(g))} "
                         f"| {pct(miss, len(g) - b)} |")
    lines += ["", f"{skipped} revisions skipped because re-running the file did not reproduce the recorded first break.",
              "A clean fork is an upper bound on what a debugger agent could hand a builder: the builder still has to "
              "pick a change that fits the brief, and a fork that tunes a number can hide the real fault.", ""]
    (OUT / "bench.md").write_text("\n".join(lines))
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
