"""Build history/results/results.md from the world JSON, beside 1d's picture and text worlds. Never edit it by hand.

    python -m history.report

Uses the latest run per world, 1d's broken worlds (harder/results/runs) and 1e's (history/results/runs).
"""

from __future__ import annotations

import json
from pathlib import Path

from loop.models import MODELS
from harder.settings import BREAKS, RUNS_DIR as RUNS_1D
from history import budget
from history.settings import BRIEFS, RESULTS_DIR, RUNS_DIR

READBACKS = ("picture", "text", "history")
WHERE = {"shot": "calculable", "cup": "calculable", "stack": "contact", "catapult": "contact", "door": "hidden cause"}


def load(runs_dir: Path) -> list[dict]:
    latest = {}
    for p in sorted(runs_dir.glob("*/*/world.json")):
        w = json.loads(p.read_text())
        latest[w["world"]] = w
    return list(latest.values())


def worlds() -> list[dict]:
    ws = [w for w in load(RUNS_1D) if w["kind"] == "broken"] + load(RUNS_DIR)
    return [w for w in ws if not w.get("dry_run")]


def n_of(ws, key) -> str:
    vals = [w.get(key) for w in ws if w.get(key) is not None]
    return f"{sum(bool(v) for v in vals)} of {len(vals)}" if vals else "n/a"


def fixed(ws) -> str:
    return f"{sum(w['passes_final'] for w in ws)} of {len(ws)}"


def main() -> None:
    ws = worlds()
    ms = [m for m in MODELS if any(w["model"] == m for w in ws)]
    s = budget.spent()
    out = ["# Experiment 1e results: the run in words", "",
           f"Generated by `python -m history.report` from the world JSON; never edited by hand. 1d's picture and text "
           f"worlds beside 1e's history worlds, the same 40 broken worlds each. 1e spend ${s['exp1e']:.2f}; all "
           f"experiments ${sum(s.values()):.2f}.", "",
           "## Broken worlds fixed, by readback", "",
           "| Readback | Both models | Opus 5.5 | GPT-6.1 Sol | Said it works while broken | Fixes after round 1 | Cost per world |",
           "|---|---|---|---|---|---|---|"]
    for a in READBACKS:
        rs = [w for w in ws if w["arm"] == a]
        if not rs:
            continue
        per = [fixed([w for w in rs if w["model"] == m]) for m in ms]
        unfixed = [w for w in rs if not w["passes_final"]]
        late = sum(1 for w in rs if w["passes_final"] and (w.get("passed_at_round") or 0) > 1)
        out.append(f"| {a} | {fixed(rs)} | " + " | ".join(per) + f" | {sum(1 for w in unfixed if w.get('claims_works'))} of "
                   f"{len(unfixed)} | {late} of {sum(w['passes_final'] for w in rs)} | "
                   f"${sum(w['cost_usd'] for w in rs) / len(rs):.3f} |")
    out += ["", "## Where the failure lives", "",
            "| Failure | Briefs | " + " | ".join(READBACKS) + " |", "|---|---|" + "---|" * len(READBACKS)]
    for kind in ("calculable", "contact", "hidden cause"):
        bs = [b for b in BRIEFS if WHERE[b] == kind]
        out.append(f"| {kind} | {', '.join(bs)} | " + " | ".join(fixed([w for w in ws if w["arm"] == a and w["brief"] in bs])
                                                         for a in READBACKS) + " |")
    out += ["", "## By brief and model", "",
            "| Brief | The break | Model | " + " | ".join(READBACKS) + " |", "|---|---|---|" + "---|" * len(READBACKS)]
    for b in BRIEFS:
        for m in ms:
            out.append(f"| {b} | {BREAKS[b][2]} | {MODELS[m].label} | " + " | ".join(
                fixed([w for w in ws if w["arm"] == a and w["brief"] == b and w["model"] == m]) for a in READBACKS) + " |")
    out += ["", "## Claims", "",
            "| Readback | Model | Tried a fix | Model's last claim right | Rounds used |", "|---|---|---|---|---|"]
    for a in READBACKS:
        for m in ms:
            rs = [w for w in ws if w["arm"] == a and w["model"] == m]
            if rs:
                out.append(f"| {a} | {MODELS[m].label} | {n_of(rs, 'tried_fix')} | {n_of(rs, 'claim_correct')} | "
                           f"{sum(w['rounds'] for w in rs) / len(rs):.1f} |")
    summary = RESULTS_DIR / "summary.md"
    if summary.exists():
        out += ["", "## Summary", "", summary.read_text().strip()]
    (RESULTS_DIR / "results.md").write_text("\n".join(out) + "\n")
    print("\n".join(out))


if __name__ == "__main__":
    main()
