"""Constants for experiment 1d, harder worlds. Anything that changes a result lives here, so it is logged by commit.

Two kinds of world. Broken: one of 1c's five hand-written worlds with one deliberate break that only running
it reveals, handed to the model to check and fix from its brief. New: two briefs built around things that
don't happen (a domino that stays up, a ball that never arrives), written from scratch as in 1c. Every brief
puts its measurement in words that admit one reading. Tests (harder/tests.py) are written before any model
run and never shown to the models.
"""

from config import ROOT
from worlds.settings import BRIEFS as BRIEFS_1C

HARDER_DIR = ROOT / "harder"
RESULTS_DIR = HARDER_DIR / "results"
RUNS_DIR = RESULTS_DIR / "runs"
SPEND_LEDGER = RESULTS_DIR / "spend.jsonl"  # 1d's own; the cap check adds experiments 1, 1b and 1c
DRYRUN_DIR = ROOT / ".dryrun" / "harder"
FIXTURES_DIR = HARDER_DIR / "fixtures"  # hand-written worlds for the new briefs; never sent to a model
BROKEN_DIR = HARDER_DIR / "broken"  # the broken worlds as sent, generated by `python -m harder.breaks`
FIXTURES_1C = ROOT / "worlds" / "fixtures"

SIM_SECONDS = 6.0
START_KEY = "start"

# 1c's briefs, with the catapult's distance named as one measurement (journal decision log, 2026-10-04).
CATAPULT_BRIEF = "a catapult throws a ball into a bucket whose centre is 3 m from where the ball starts"

BRIEFS = {
    "shot": dict(BRIEFS_1C["shot"], kind="broken", test="shot"),
    "cup": dict(BRIEFS_1C["cup"], kind="broken", test="cup"),
    "door": dict(BRIEFS_1C["door"], kind="broken", test="door"),
    "stack": dict(BRIEFS_1C["stack"], kind="broken", test="stack"),
    "catapult": dict(BRIEFS_1C["catapult"], brief=CATAPULT_BRIEF, kind="broken", test="catapult"),
    "dominoes": {
        "brief": "ten dominoes stand in a row; the first is tipped over and knocks down the rest, and every domino "
                 "ends tilted at least 15 degrees from upright",
        "names": "The dominoes are bodies named `domino1` (the first to fall) to `domino10`, each with a "
                 "`<freejoint/>` and one box geom whose longest side is its height.",
        "kind": "new", "test": "dominoes",
    },
    "pendulum": {
        "brief": "a pendulum swings down and strikes a ball resting on the floor, which rolls into a cup whose centre "
                 "is 1 m from where the ball starts",
        "names": "The pendulum is a body named `pendulum` on a hinge joint; every geom of the pendulum is named with "
                 "the prefix `pendulum`. The ball is a body named `ball` with a `<freejoint/>` and one sphere geom "
                 "named `ball`. The cup is a body named `cup`; all its geoms belong to it.",
        "kind": "new", "test": "pendulum",
    },
}

# One break per 1c fixture: (exact text in the fixture, replacement, what running shows). Settled in MuJoCo
# before any model run; each fails its own pre-registered test (python -m harder.selftest).
BREAKS = {
    "shot": ('qvel="3.21 0 9.3 0 0 0"', 'qvel="3.21 0 9.3 0 -30 0"',
             "backspin added to the launch: the ball comes down 0.58 m short of the rim"),
    "cup": ('<body name="cup" pos="2.0500 0 0">', '<body name="cup" pos="2.6500 0 0">',
            "the cup moved 0.6 m further away: the ball lands and stops short of it"),
    "door": ('range="0 120"', 'range="0 2.1"',
             "the hinge range written as if in radians, which MuJoCo reads in degrees: the limit snaps the open door "
             "shut at once, so it never swings"),
    "stack": ('  3.0 0 0 0 0 0"', '  1.5 0 0 0 0 0"',
              "the pusher's speed halved: it shoves the stack without toppling it"),
    "catapult": ('stiffness="3.0"', 'stiffness="2.0"',
                 "the catapult's spring weakened by a third: the ball falls short of the bucket"),
}

ARMS = ("picture", "text")
MAX_ROUNDS = 3
MAX_LOAD_RETRIES = 2
MODELS = ("opus-5.5", "gpt-6.1")
SEEDS = (0, 1, 2, 3)

VIEW = "drafting"  # as in 1c
RES = 128
RESIDUE_COPIES = 24
REST_SPEED = 0.05
