"""After 1f: check each language world's own `expect` lines against its final run. No model calls, no spend.

    python -m langrun.expects        # writes langrun/results/expects.md

1f's judge never read the models' expect blocks; this asks whether they would have caught the misses. Uses the
latest run per world and the last file that built. Each line is checked twice: by the language's own checker
(typed/lang.py, on the replay's events) and by langrun/expect.py, which fixes its two faults.
"""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

from typed.lang import LIBRARY, compile_program, expectations, parse
from typed.replay import replay
from worlds.tests import run as run_world
from langrun import expect
from langrun.settings import RESULTS_DIR, RUNS_DIR


def main() -> None:
    latest = {}
    for p in sorted(RUNS_DIR.glob("*__language__*/*/world.json")):
        w = json.loads(p.read_text())
        latest[w["world"]] = (w, p.parent)
    tally, rows = Counter(), []
    for wid, (w, d) in sorted(latest.items()):
        built = [f for f in w["files"] if not f.get("problem")]
        if not built:
            continue
        label = built[-1]["label"]
        library = LIBRARY.read_text()
        if (d / f"{label}.parts").exists():
            library = library.rstrip() + "\n\n\n" + (d / f"{label}.parts").read_text()
        prog = parse((d / f"{label}.world").read_text(), library)
        c = compile_program(prog)
        old = expectations(prog, replay(c).events())
        new = expect.check([line for _, line in prog.expect], run_world(c.xml), c.owner)
        test = "works" if w["passes_final"] else "fails its test"
        for name, ex in (("language's checker", old), ("fixed checker", new)):
            verdict = "no expect block" if not ex else "all hold" if all(ok for _, ok, _ in ex) else "one or more fail"
            tally[(name, test, verdict)] += 1
        for (line, ok0, ev0), (_, ok1, ev1) in zip(old, new):
            if not (ok0 and ok1):
                rows.append(f"| {wid} | {test} | `{line}` | {'holds' if ok0 else ev0} | {'holds' if ok1 else ev1} |")
    out = ["# 1f: the models' own expect lines, checked after the run", "",
           "Generated by `python -m langrun.expects`; never edited by hand.", "",
           "| Checker | Test result | Expect lines | Worlds |", "|---|---|---|---|"]
    out += [f"| {a} | {b} | {c} | {n} |" for (a, b, c), n in sorted(tally.items())]
    out += ["", "## Every expect line either checker failed", "",
            "| World | Test | Line | Language's checker | Fixed checker |", "|---|---|---|---|---|"]
    out += rows
    (RESULTS_DIR / "expects.md").write_text("\n".join(out) + "\n")
    print("\n".join(out))


if __name__ == "__main__":
    main()
