"""Build langrun/results/results.md from the world JSON. Never edit it by hand.

    python -m langrun.report
    python -m langrun.report --runs .dryrun/langrun/runs --out .dryrun/langrun     # against dry runs
    python -m langrun.report --checked                                             # experiment 1g

Uses the latest run per world. A summary written after reading the tables goes in results/summary.md.
"""

from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path

from loop.models import MODELS
from history import budget
from langrun.settings import ARMS, BRIEFS, CHECKED_RESULTS_DIR, CHECKED_RUNS_DIR, CONTROL_RUNS_DIR, RESULTS_DIR, RUNS_DIR


def load(runs_dir: Path) -> list[dict]:
    latest = {}
    for p in sorted(runs_dir.glob("*/*/world.json")):
        w = json.loads(p.read_text())
        latest[w["world"]] = w
    return list(latest.values())


def frac(ws, key) -> str:
    vals = [w.get(key) for w in ws if w.get(key) is not None]
    return f"{sum(bool(v) for v in vals)} of {len(vals)}" if vals else "n/a"


def code(problem: str | None) -> str:
    """The first line of a problem, shortened: an Elm-style header's code, or MuJoCo's own message."""
    if not problem:
        return ""
    for line in problem.splitlines():
        if line.startswith("-- "):
            return line[3:].split(" ---")[0].strip()
    return problem.split(":")[0][:60]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--runs", type=Path, default=RUNS_DIR)
    ap.add_argument("--out", type=Path, default=RESULTS_DIR)
    ap.add_argument("--checked", action="store_true", help="experiment 1g, beside 1f")
    args = ap.parse_args()
    if args.checked:
        return checked(args)
    ws = load(args.runs)
    ms = [m for m in MODELS if any(w["model"] == m for w in ws)]
    seeds = sorted({w["seed"] for w in ws})
    s = budget.spent()
    out = ["# Experiment 1f results: the language run", "",
           f"Generated by `python -m langrun.report` from the world JSON; never edited by hand. {len(ws)} worlds, seeds "
           f"{', '.join(map(str, seeds))}. 1f spend ${s['exp1f']:.2f}; 1e and 1f ${s['exp1e'] + s['exp1f']:.2f}; all "
           f"experiments ${sum(s.values()):.2f}.", "",
           "## Works in the end, by arm", "",
           "| Arm | All briefs | 1d's seven | Held-out three | Builds on first write | Works as first written | "
           "Cost per world |", "|---|---|---|---|---|---|---|"]
    for a in ARMS:
        rs = [w for w in ws if w["arm"] == a]
        if not rs:
            continue
        d1 = [w for w in rs if w["set"] == "1d"]
        ho = [w for w in rs if w["set"] == "held-out"]
        built_first = sum(1 for w in rs if not (w["files"] and w["files"][0].get("problem")))
        out.append(f"| {a} | {frac(rs, 'passes_final')} | {frac(d1, 'passes_final')} | {frac(ho, 'passes_final')} | "
                   f"{built_first} of {len(rs)} | {frac(rs, 'passes_first')} | ${sum(w['cost_usd'] for w in rs) / len(rs):.3f} |")
    out += ["", "## By model", "", "| Model | Arm | Works in the end | 1d's seven | Held-out three | Model's last claim right | "
            "Never built | Cost per world |", "|---|---|---|---|---|---|---|---|"]
    for m in ms:
        for a in ARMS:
            rs = [w for w in ws if w["arm"] == a and w["model"] == m]
            if rs:
                out.append(f"| {MODELS[m].label} | {a} | {frac(rs, 'passes_final')} | "
                           f"{frac([w for w in rs if w['set'] == '1d'], 'passes_final')} | "
                           f"{frac([w for w in rs if w['set'] == 'held-out'], 'passes_final')} | {frac(rs, 'claim_correct')} | "
                           f"{sum(1 for w in rs if not w['loads'])} | ${sum(w['cost_usd'] for w in rs) / len(rs):.3f} |")
    out += ["", "## By brief (both models, all seeds)", "",
            "| Brief | Set | Library part for it | " + " | ".join(ARMS) + " |", "|---|---|---|" + "---|" * len(ARMS)]
    for b, B in BRIEFS.items():
        out.append(f"| {b} | {B['set']} | {'yes' if B['kind'] == 'library' else 'no'} | " + " | ".join(
            frac([w for w in ws if w["arm"] == a and w["brief"] == b], "passes_final") for a in ARMS) + " |")
    out += ["", "## Problems the checks raised before a run", "",
            "Every file that did not run, by the first line of its problem.", "", "| Arm | Problem | Files |", "|---|---|---|"]
    for a in ARMS:
        c = Counter(code(f.get("problem")) for w in ws if w["arm"] == a for f in w["files"] if f.get("problem"))
        for k, n in c.most_common():
            out.append(f"| {a} | {k} | {n} |")
    out += ["", "## Every world", "", "| World | Builds | Works first | Works in the end | Rounds | Failing checks or problem at the end |",
            "|---|---|---|---|---|---|"]
    for w in sorted(ws, key=lambda w: (w["brief"], w["arm"], w["model"], w["seed"])):
        fail = code(w.get("final_problem")) or ", ".join(k for k, v in (w.get("final_checks") or {}).items() if not v)
        out.append(f"| {w['world']} | {w['loads']} | {w['passes_first']} | {w['passes_final']} | {w['rounds']} | {fail} |")
    summary = args.out / "summary.md"
    if summary.exists():
        out += ["", "## Summary", "", summary.read_text().strip()]
    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "results.md").write_text("\n".join(out) + "\n")
    print("\n".join(out))


def checked(args) -> None:
    """1g beside its control and 1f. The control has the fixed language, the history and the rest line, but no
    expectations, so 1g against the control is the effect of checking expectations alone."""
    runs = args.runs if args.runs != RUNS_DIR else CHECKED_RUNS_DIR
    outdir = args.out if args.out != RESULTS_DIR else CHECKED_RESULTS_DIR
    g = load(runs)
    f = [w for w in load(RUNS_DIR) if not w.get("dry_run")]
    ctl = [w for w in load(CONTROL_RUNS_DIR) if not w.get("dry_run")]
    s = budget.spent()
    out = ["# Experiment 1g results: expectations checked", "",
           f"Generated by `python -m langrun.report --checked` from the world JSON; never edited by hand. {len(g)} 1g worlds "
           f"beside {len(ctl)} control worlds and 1f's {len(f)}. 1g spend (control included) ${s['exp1g']:.2f}; all experiments ${sum(s.values()):.2f}.", "",
           "## Works in the end", "",
           "| Arm | 1f (seeds 0, 1) | Control | 1g | Control, 1d's seven | 1g, 1d's seven | Control, held-out three | 1g, held-out three | 1g builds on first write | 1g works as first written | "
           "1g cost per world |", "|---|---|---|---|---|---|---|---|---|---|---|"]
    for a in ARMS:
        rs, fs = [w for w in g if w["arm"] == a], [w for w in f if w["arm"] == a]
        if not rs:
            continue
        built_first = sum(1 for w in rs if not (w["files"] and w["files"][0].get("problem")))
        cs = [w for w in ctl if w["arm"] == a]
        out.append(f"| {a} | {frac(fs, 'passes_final')} | {frac(cs, 'passes_final')} | {frac(rs, 'passes_final')} | "
                   f"{frac([w for w in cs if w['set'] == '1d'], 'passes_final')} | "
                   f"{frac([w for w in rs if w['set'] == '1d'], 'passes_final')} | "
                   f"{frac([w for w in cs if w['set'] == 'held-out'], 'passes_final')} | "
                   f"{frac([w for w in rs if w['set'] == 'held-out'], 'passes_final')} | {built_first} of {len(rs)} | "
                   f"{frac(rs, 'passes_first')} | ${sum(w['cost_usd'] for w in rs) / len(rs):.3f} |")
    out += ["", "## Effort per world", "",
            "Model turns (writes and see-and-fix rounds), tokens and wall time per world, from the world JSON. "
            "\"To working\" counts only worlds that did not work as first written but worked in the end: the turns and "
            "output tokens spent getting there.", "",
            "| Condition | Arm | Worlds | Turns | Input tokens | Output tokens | Seconds | Cost | Turns to working | "
            "Output tokens to working |", "|---|---|---|---|---|---|---|---|---|---|"]
    for name, ws in (("1f", f), ("control", ctl), ("1g", g)):
        for a in ARMS:
            rs = [w for w in ws if w["arm"] == a]
            if not rs:
                continue
            fixed = [w for w in rs if w["passes_final"] and not w["passes_first"]]
            def till(w):
                n = 0
                for t in w["turns"]:
                    n += 1
                    if t.get("new_file_passed"):
                        break
                return n, sum(t["usage"]["output_tokens"] for t in w["turns"][:n])
            tl = [till(w) for w in fixed]
            avg = lambda xs: sum(xs) / len(xs) if xs else float("nan")
            out.append(f"| {name} | {a} | {len(rs)} | {avg([len(w['turns']) for w in rs]):.2f} | "
                       f"{avg([w['tokens']['input'] for w in rs]):,.0f} | {avg([w['tokens']['output'] for w in rs]):,.0f} | "
                       f"{avg([w['seconds'] for w in rs]):.0f} | ${avg([w['cost_usd'] for w in rs]):.3f} | "
                       + (f"{avg([t[0] for t in tl]):.2f} ({len(tl)} worlds) | {avg([t[1] for t in tl]):,.0f} |" if tl else "n/a | n/a |"))
    out += ["", "## By model", "", "| Model | Arm | Control | 1g | Control: last claim right | 1g: last claim right |",
            "|---|---|---|---|---|---|"]
    for m in [m for m in MODELS if any(w["model"] == m for w in g + ctl)]:
        for a in ARMS:
            cs = [w for w in ctl if w["arm"] == a and w["model"] == m]
            rs = [w for w in g if w["arm"] == a and w["model"] == m]
            out.append(f"| {MODELS[m].label} | {a} | {frac(cs, 'passes_final')} | {frac(rs, 'passes_final')} | "
                       f"{frac(cs, 'claim_correct')} | {frac(rs, 'claim_correct')} |")
    out += ["", "## Did the expectations judge well?", "",
            "At the end of each world: whether its own expectations all held, against whether its test passed.", "",
            "| Arm | Model | Test passes, expectations hold | Test passes, one fails | Test fails, one fails | "
            "Test fails, all hold | No expectations | Model's last claim right |", "|---|---|---|---|---|---|---|---|"]
    for a in ARMS:
        for m in [m for m in MODELS if any(w["model"] == m for w in g)]:
            rs = [w for w in g if w["arm"] == a and w["model"] == m]
            if not rs:
                continue
            c = Counter((w["passes_final"], w.get("expect_all_hold")) for w in rs)
            out.append(f"| {a} | {MODELS[m].label} | {c[(True, True)]} | {c[(True, False)]} | {c[(False, False)]} | "
                       f"{c[(False, True)]} | {c[(True, None)] + c[(False, None)]} | {frac(rs, 'claim_correct')} |")
    out += ["", "## By brief (both models, both seeds)", "", "| Brief | Set | " + " | ".join(f"{a} control | {a} 1g" for a in ARMS) +
            " |", "|---|---|" + "---|---|" * len(ARMS)]
    for b, B in BRIEFS.items():
        out.append(f"| {b} | {B['set']} | " + " | ".join(
            f"{frac([w for w in ctl if w['arm'] == a and w['brief'] == b], 'passes_final')} | "
            f"{frac([w for w in g if w['arm'] == a and w['brief'] == b], 'passes_final')}" for a in ARMS) + " |")
    out += ["", "## Problems the checks raised before a run (control and 1g)", "", "| Arm | Problem | Files |", "|---|---|---|"]
    for a in ARMS:
        c = Counter(code(x.get("problem")) for w in g + ctl if w["arm"] == a for x in w["files"] if x.get("problem"))
        out += [f"| {a} | {k} | {n} |" for k, n in c.most_common()]
    out += ["", "## Every control world that fails its test", "", "| World | Failing checks |", "|---|---|"]
    for w in sorted(ctl, key=lambda w: w["world"]):
        if not w["passes_final"]:
            fail = code(w.get("final_problem")) or ", ".join(k for k, v in (w.get("final_checks") or {}).items() if not v)
            out.append(f"| {w['world']} | {fail} |")
    out += ["", "## Every 1g world that fails its test, or whose expectations fail at the end", "",
            "| World | Works in the end | Failing checks | Expectations that do not hold |", "|---|---|---|---|"]
    for w in sorted(g, key=lambda w: w["world"]):
        bad = [f"`{line}`: {ev}" for line, ok, ev in (w.get("final_expect") or []) if not ok]
        if not w["passes_final"] or bad:
            fail = code(w.get("final_problem")) or ", ".join(k for k, v in (w.get("final_checks") or {}).items() if not v)
            out.append(f"| {w['world']} | {w['passes_final']} | {fail} | {'; '.join(bad)} |")
    summary = outdir / "summary.md"
    if summary.exists():
        out += ["", "## Summary", "", summary.read_text().strip()]
    outdir.mkdir(parents=True, exist_ok=True)
    (outdir / "results.md").write_text("\n".join(out) + "\n")
    print("\n".join(out))


if __name__ == "__main__":
    main()
