"""Build langrun/results/results.md from the world JSON. Never edit it by hand.

    python -m langrun.report
    python -m langrun.report --runs .dryrun/langrun/runs --out .dryrun/langrun     # against dry runs

Uses the latest run per world. A summary written after reading the tables goes in results/summary.md.
"""

from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path

from loop.models import MODELS
from history import budget
from langrun.settings import ARMS, BRIEFS, RESULTS_DIR, RUNS_DIR


def load(runs_dir: Path) -> list[dict]:
    latest = {}
    for p in sorted(runs_dir.glob("*/*/world.json")):
        w = json.loads(p.read_text())
        latest[w["world"]] = w
    return list(latest.values())


def frac(ws, key) -> str:
    vals = [w.get(key) for w in ws if w.get(key) is not None]
    return f"{sum(bool(v) for v in vals)} of {len(vals)}" if vals else "n/a"


def code(problem: str | None) -> str:
    """The first line of a problem, shortened: an Elm-style header's code, or MuJoCo's own message."""
    if not problem:
        return ""
    for line in problem.splitlines():
        if line.startswith("-- "):
            return line[3:].split(" ---")[0].strip()
    return problem.split(":")[0][:60]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--runs", type=Path, default=RUNS_DIR)
    ap.add_argument("--out", type=Path, default=RESULTS_DIR)
    args = ap.parse_args()
    ws = load(args.runs)
    ms = [m for m in MODELS if any(w["model"] == m for w in ws)]
    seeds = sorted({w["seed"] for w in ws})
    s = budget.spent()
    out = ["# Experiment 1f results: the language run", "",
           f"Generated by `python -m langrun.report` from the world JSON; never edited by hand. {len(ws)} worlds, seeds "
           f"{', '.join(map(str, seeds))}. 1f spend ${s['exp1f']:.2f}; 1e and 1f ${s['exp1e'] + s['exp1f']:.2f}; all "
           f"experiments ${sum(s.values()):.2f}.", "",
           "## Works in the end, by arm", "",
           "| Arm | All briefs | 1d's seven | Held-out three | Builds on first write | Works as first written | "
           "Cost per world |", "|---|---|---|---|---|---|---|"]
    for a in ARMS:
        rs = [w for w in ws if w["arm"] == a]
        if not rs:
            continue
        d1 = [w for w in rs if w["set"] == "1d"]
        ho = [w for w in rs if w["set"] == "held-out"]
        built_first = sum(1 for w in rs if not (w["files"] and w["files"][0].get("problem")))
        out.append(f"| {a} | {frac(rs, 'passes_final')} | {frac(d1, 'passes_final')} | {frac(ho, 'passes_final')} | "
                   f"{built_first} of {len(rs)} | {frac(rs, 'passes_first')} | ${sum(w['cost_usd'] for w in rs) / len(rs):.3f} |")
    out += ["", "## By model", "", "| Model | Arm | Works in the end | 1d's seven | Held-out three | Model's last claim right | "
            "Never built | Cost per world |", "|---|---|---|---|---|---|---|---|"]
    for m in ms:
        for a in ARMS:
            rs = [w for w in ws if w["arm"] == a and w["model"] == m]
            if rs:
                out.append(f"| {MODELS[m].label} | {a} | {frac(rs, 'passes_final')} | "
                           f"{frac([w for w in rs if w['set'] == '1d'], 'passes_final')} | "
                           f"{frac([w for w in rs if w['set'] == 'held-out'], 'passes_final')} | {frac(rs, 'claim_correct')} | "
                           f"{sum(1 for w in rs if not w['loads'])} | ${sum(w['cost_usd'] for w in rs) / len(rs):.3f} |")
    out += ["", "## By brief (both models, all seeds)", "",
            "| Brief | Set | Library part for it | " + " | ".join(ARMS) + " |", "|---|---|---|" + "---|" * len(ARMS)]
    for b, B in BRIEFS.items():
        out.append(f"| {b} | {B['set']} | {'yes' if B['kind'] == 'library' else 'no'} | " + " | ".join(
            frac([w for w in ws if w["arm"] == a and w["brief"] == b], "passes_final") for a in ARMS) + " |")
    out += ["", "## Problems the checks raised before a run", "",
            "Every file that did not run, by the first line of its problem.", "", "| Arm | Problem | Files |", "|---|---|---|"]
    for a in ARMS:
        c = Counter(code(f.get("problem")) for w in ws if w["arm"] == a for f in w["files"] if f.get("problem"))
        for k, n in c.most_common():
            out.append(f"| {a} | {k} | {n} |")
    out += ["", "## Every world", "", "| World | Builds | Works first | Works in the end | Rounds | Failing checks or problem at the end |",
            "|---|---|---|---|---|---|"]
    for w in sorted(ws, key=lambda w: (w["brief"], w["arm"], w["model"], w["seed"])):
        fail = code(w.get("final_problem")) or ", ".join(k for k, v in (w.get("final_checks") or {}).items() if not v)
        out.append(f"| {w['world']} | {w['loads']} | {w['passes_first']} | {w['passes_final']} | {w['rounds']} | {fail} |")
    summary = args.out / "summary.md"
    if summary.exists():
        out += ["", "## Summary", "", summary.read_text().strip()]
    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "results.md").write_text("\n".join(out) + "\n")
    print("\n".join(out))


if __name__ == "__main__":
    main()
