"""Where 1h's failures come from: each failed world's first failing hidden-test line, sorted into causes, and the
pass counts again under a lenient reading (a hinge may reach either stop; order within 0.1 s counts). No model calls.

    python -m hundred.failures        # writes hundred/results/failures.md
"""

from __future__ import annotations

import collections
import glob
import json
import re
from pathlib import Path

from hundred import hidden
from hundred.settings import ARMS, RESULTS_DIR, RUNS_DIR
from worlds.tests import run as run_world

CAUSES = [("no thing named", "a name the brief needs is missing"),
          ("never touch", "the chain breaks: two things never touch"),
          ("before the line above", "events happen out of order"),
          ("still moving", "not at rest at the end"),
          ("outside", "comes to rest outside the target"),
          ("starts", "starts in its end state"),
          ("never reaches", "a hinge never reaches the named stop"),
          ("height", "misses the opening")]


def cause(evidence: str) -> str:
    return next((c for k, c in CAUSES if k in evidence), "other")


def final_xml(w: dict, d: Path) -> str:
    for name in (f"{w['final_label']}.compiled.xml", f"{w['final_label']}.xml"):
        if (d / name).exists():
            return (d / name).read_text()
    raise FileNotFoundError(d)


def lenient(lines: list[str], r) -> bool:
    last = 0.0
    for line in lines:
        ok, t, _ = hidden.one(line, r, None)
        if not ok and line.rstrip(".").endswith("stop"):
            other = line.replace("lower", "upper") if "lower" in line else line.replace("upper", "lower")
            ok, t, _ = hidden.one(other, r, None)
        if not ok or (t is not None and t + 0.1 < last):
            return False
        last = max(last, t or 0.0)
    return not r.diverged


def main() -> int:
    ws = [(json.loads(Path(f).read_text()), Path(f).parent) for f in sorted(glob.glob(str(RUNS_DIR / "*/*/world.json")))]
    by = collections.Counter()
    gaps = collections.Counter()
    strict, loose = collections.Counter(), collections.Counter()
    for w, d in ws:
        t = w.get("final_test")
        if not t:
            by[("never built", w["arm"])] += 1
            continue
        strict[w["arm"]] += w["passes_final"]
        r = run_world(final_xml(w, d))
        loose[w["arm"]] += lenient(w["test"], r)
        if w["passes_final"]:
            continue
        first = next(line for line, ok in t["checks"].items() if not ok)
        ev = t["evidence"][first]
        by[(cause(ev), w["arm"])] += 1
        if m := re.search(r"at (\d+\.\d+) s.*\((\d+\.\d+) s\)", ev):
            gaps["within 0.1 s" if float(m[2]) - float(m[1]) <= 0.1 else "more than 0.1 s"] += 1
    causes = sorted({c for c, _ in by}, key=lambda c: -sum(by[(c, a)] for a in ARMS))
    out = ["# Where 1h's failures come from", "", "Generated by `python -m hundred.failures`; never edited by hand. "
           "Each failed world counted once, by its first failing hidden-test line.", "",
           "| Cause | " + " | ".join(ARMS) + " | All |", "|---|" + "---|" * (len(ARMS) + 1)]
    for c in causes:
        out.append(f"| {c} | " + " | ".join(str(by[(c, a)]) for a in ARMS) + f" | {sum(by[(c, a)] for a in ARMS)} |")
    out += ["", f"Out-of-order failures by gap: {dict(gaps)}.", "",
            "| Arm | Worked (strict hidden test) | Worked (either hinge stop, order within 0.1 s) |", "|---|---|---|"]
    out += [f"| {a} | {strict[a]} | {loose[a]} |" for a in ARMS]
    text = "\n".join(out) + "\n"
    (RESULTS_DIR / "failures.md").write_text(text)
    print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
