"""The judge's verdicts against the hidden test (fixed reading), beside the authors' own "it works" claims.

    python -m hundred.judge_report      # writes hundred/results/judge.md
"""

from __future__ import annotations

import collections
import glob
import json
from pathlib import Path

from hundred.settings import ARMS, JUDGE_DIR, RESULTS_DIR


def main() -> int:
    rs = [json.loads(Path(f).read_text()) for f in sorted(glob.glob(str(JUDGE_DIR / "*__*.json")))]
    c = collections.defaultdict(collections.Counter)
    for r in rs:
        for key in (r["arm"], "all"):
            k = c[key]
            k["n"] += 1
            k["unread"] += r["works"] is None
            k["broken"] += not r["test_passed"]
            k["working"] += r["test_passed"]
            k["judge_wrong_works"] += r["works"] is True and not r["test_passed"]
            k["judge_false_alarm"] += r["works"] is False and r["test_passed"]
            k["author_wrong_works"] += r["author_claims_works"] and not r["test_passed"]
            k["both_wrong_works"] += r["author_claims_works"] and r["works"] is True and not r["test_passed"]
            k["agree"] += r["works"] is not None and r["works"] == r["test_passed"]
            k["cost"] += r["cost_usd"]
            k["out"] += r["tokens"]["output"]
    judges = sorted({r["judge"] for r in rs})
    out = ["# An independent judge on 1h's runs", "",
           f"Generated by `python -m hundred.judge_report`; never edited by hand. Judge: {', '.join(judges)}. It read the "
           "brief, its thing names, the settle check and the run in words, never the hidden test or the author's claim. "
           "Truth is the hidden test, fixed reading (hidden.py). Worlds never built are left out.", "",
           "| Arm | Worlds judged | Broken | Author said works, broken | Judge said works, broken | Both said works, broken "
           "| Judge said broken, works | Judge agrees with test | Cost |", "|---|---|---|---|---|---|---|---|---|"]
    for a in (*ARMS, "all"):
        k = c[a]
        if not k["n"]:
            continue
        out.append(f"| {a} | {k['n']} | {k['broken']} | {k['author_wrong_works']} | {k['judge_wrong_works']} | "
                   f"{k['both_wrong_works']} | {k['judge_false_alarm']} of {k['working']} | {k['agree']} of {k['n']} | "
                   f"${k['cost']:.2f} |")
    k = c["all"]
    out += ["", f"Unreadable verdicts: {k['unread']}. Judge output tokens: {k['out']:,} in all.", "",
            "\"Both said works, broken\" is what an author's \"it works\" would still get wrong if it had to pass the judge too.", "",
            "## Broken worlds the judge passed", ""]
    for r in rs:
        if r["works"] is True and not r["test_passed"]:
            first = next(line for line, ev in r["test_evidence"].items() if line in r["test_evidence"] and
                         not _ok(r, line))
            out.append(f"- {r['world']}: hidden test fails at \"{first}\": {r['test_evidence'][first]}")
    out += ["", "## Working worlds the judge failed", ""]
    for r in rs:
        if r["works"] is False and r["test_passed"]:
            out.append(f"- {r['world']}: \"{r['first_failure']}\"")
    text = "\n".join(out) + "\n"
    (RESULTS_DIR / "judge.md").write_text(text)
    print(text)
    return 0


def _ok(r: dict, line: str) -> bool:
    return r.get("test_checks", {}).get(line, False)


if __name__ == "__main__":
    raise SystemExit(main())
