"""Where long chains break, and whether a fix keeps the links before it ($0, no model calls).

    python -m ladder.breaks            # re-runs every file: ladder/results_breaks/breaks.json
    python -m ladder.breaks --report   # tables from breaks.json: ladder/results_breaks/breaks.md

Re-runs every file each 8- and 16-step world wrote (1j, 1k, 1l), in the order it wrote them, against the hidden test,
and asks three questions a link-by-link builder depends on:
  - Is a world's held set a prefix of its chain (everything before the first break holds, nothing after)?
  - When a later file changes the world, do links that held before stop holding (a fix that is not local)?
  - When the author read a failing run, did their verdict name the parts of the first broken link?
"""

from __future__ import annotations

import collections
import json
import re
import sys
from pathlib import Path

from config import ROOT
from hundred import hidden
from hundred.hidden import names_in
from hundred.settings import SIM_SECONDS
from typed.lang import LIBRARY, compile_program, parse
from worlds.tests import run as run_world

LADDER = ROOT / "ladder"
SOURCES = {"1j": LADDER / "results" / "runs", "1k": LADDER / "results_1k" / "runs", "1l": LADDER / "results_1l" / "runs"}
OUT = LADDER / "results_breaks"


def files_in_order(run_dir: Path, arm: str) -> list[tuple[str, Path]]:
    ext = "world" if arm == "language" else "xml"
    found = []
    for p in run_dir.glob(f"*.{ext}"):
        if p.name.endswith(".compiled.xml"):
            continue
        m = re.fullmatch(r"(written|round)(\d+)", p.stem)
        if m:
            found.append(((0 if m[1] == "written" else 1, int(m[2])), p.stem, p))
    return [(label, p) for _, label, p in sorted(found)]


def test_file(p: Path, arm: str, test: list[str]) -> dict | None:
    owner = None
    if arm == "language":
        library = LIBRARY.read_text()
        parts = p.with_suffix(".parts")
        if parts.exists():
            library = library.rstrip() + "\n\n\n" + parts.read_text()
        try:
            c = compile_program(parse(p.read_text(), library))
        except Exception:
            return None
        if c.problems:
            return None
        xml, owner = c.xml, c.owner
    else:
        xml = p.read_text()
    try:
        r = run_world(xml, seconds=SIM_SECONDS)
    except Exception:
        return None
    return hidden.judge(test, r, owner)


def held_list(test: list[str], checks: dict) -> list[bool]:
    return [bool(checks[line]) for line in test]


def first_break(held: list[bool]) -> int:
    return next((i for i, x in enumerate(held) if not x), len(held))


def report() -> int:
    rows = json.loads((OUT / "breaks.json").read_text())
    c = collections.defaultdict(collections.Counter)
    for r in rows:
        a, seq = r["arm"], r["files"]
        for s in seq:
            f = first_break(s["held"])
            c[a]["files"] += 1
            c[a]["prefix"] += not any(s["held"][f:])
        for p, q in zip(seq, seq[1:]):
            fp, fq = first_break(p["held"]), first_break(q["held"])
            c[a]["revisions"] += 1
            c[a]["advanced"] += fq > fp
            c[a]["stuck"] += fq == fp
            c[a]["lost earlier"] += any(not q["held"][i] for i in range(fp))
        if seq and first_break(seq[-1]["held"]) < len(r["test"]):
            line = r["test"][first_break(seq[-1]["held"])]
            c[a]["final breaks"] += 1
            c[a]["final swings"] += "swings" in line
        if a == "blind":
            continue
        rec = json.loads((Path(r["dir"]) / "world.json").read_text())
        labels = [s["label"] for s in seq]
        by_label = {s["label"]: s for s in seq}
        for t in rec["turns"]:
            if not t["turn"].startswith("round") or "verdict" not in t or t.get("current_passed"):
                continue
            n = int(t["turn"][5:])
            before = [l for l in labels if l.startswith("written") or (l.startswith("round") and int(l[5:]) < n)]
            if not before:
                continue
            s = by_label[before[-1]]
            f = first_break(s["held"])
            if f == len(s["held"]):
                continue
            v = t["verdict"] if isinstance(t["verdict"], str) else json.dumps(t["verdict"])
            c[a]["verdicts"] += 1
            c[a]["named"] += all(re.search(r"\b" + re.escape(nm) + r"\b", v, re.I) for nm in names_in(r["test"][f]))
    pct = lambda n, d: f"{n} of {d} ({100 * n / d:.0f}%)" if d else "none"
    lines = ["# Where long chains break (1j, 1k, 1l; $0)", "",
             "Generated by `python -m ladder.breaks --report`; never edited by hand. Every file each 8- and 16-step world "
             "wrote was re-run against the hidden test, in the order it was written. Blind XML never saw a run; its later "
             "files answer load errors only.", "",
             "| Arm | Worlds | Files | Held set is a prefix of the chain | Revisions | Moved the first break forward "
             "| Left the first break where it was | Broke a link that held before | Verdict named the first broken link's parts "
             "| Final first break is a swing |",
             "|---|---|---|---|---|---|---|---|---|---|"]
    for a in ("blind", "xml", "language"):
        k = c[a]
        lines.append(f"| {a} | {sum(r['arm'] == a for r in rows)} | {k['files']} | {pct(k['prefix'], k['files'])} "
                     f"| {k['revisions']} | {pct(k['advanced'], k['revisions'])} | {pct(k['stuck'], k['revisions'])} "
                     f"| {pct(k['lost earlier'], k['revisions'])} | {pct(k['named'], k['verdicts']) if a != 'blind' else 'no run seen'} "
                     f"| {pct(k['final swings'], k['final breaks'])} |")
    lines += ["", "\"Named\" means the verdict mentions every part the broken test line names; a verdict can describe the "
              "break without naming both parts, so this undercounts.", ""]
    (OUT / "breaks.md").write_text("\n".join(lines))
    print("\n".join(lines))
    return 0


def main() -> int:
    if "--report" in sys.argv:
        return report()
    OUT.mkdir(parents=True, exist_ok=True)
    rows = []
    for exp, root in SOURCES.items():
        for f in sorted(root.glob("*/*/world.json")):
            rec = json.loads(f.read_text())
            if rec["steps"] < 8 or (exp != "1j" and rec["arm"] != "language"):
                continue
            seq = []
            for label, p in files_in_order(f.parent, rec["arm"]):
                v = test_file(p, rec["arm"], rec["test"])
                if v is not None:
                    seq.append({"label": label, "held": held_list(rec["test"], v["checks"]),
                                "evidence": v["evidence"]})
            rows.append({"exp": exp, "world": rec["world"], "arm": rec["arm"], "steps": rec["steps"],
                         "family": rec["family"], "test": rec["test"], "files": seq, "dir": str(f.parent)})
            print(exp, rec["world"], [sum(s["held"]) for s in seq], flush=True)
    (OUT / "breaks.json").write_text(json.dumps(rows, indent=1) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
