"""1l against 1k and 1j at 8 and 16 steps: the language with slides and numeric bounce beside the earlier arms.
No model calls.

    python -m ladder.report_1l      # writes ladder/results_1l/results.md
"""

from __future__ import annotations

import collections

from ladder.report_1k import LEVELS, REFUSED, load
from ladder.settings import JUDGE_DIR, RUNS_DIR, rerun_dir
from langrun.report import fisher

DECLINED = "could not find a ```world"  # the reply had no world in it: the author declined, or forgot the block


def main() -> int:
    d1k, d1l = rerun_dir("1k"), rerun_dir("1l")
    ws = load(RUNS_DIR, JUDGE_DIR, {"blind": "blind XML (1j)", "xml": "XML + words (1j)", "language": "language (1j)"}) + \
        load(d1k / "runs", d1k / "judge", {"language": "language, positions fixed (1k)"}) + \
        load(d1l / "runs", d1l / "judge", {"language": "language, slides and bounce (1l)"})
    rows = ["blind XML (1j)", "XML + words (1j)", "language (1j)", "language, positions fixed (1k)",
            "language, slides and bounce (1l)"]
    c = collections.defaultdict(collections.Counter)
    for w in ws:
        k = (w["steps"], w["row"])
        t = w.get("final_test") or {}
        c[k]["n"] += 1
        c[k]["built"] += bool(t)
        c[k]["worked"] += w["passes_final"]
        c[k]["held"] += sum(bool(v) for line, v in t.get("checks", {}).items() if line in w["test"])
        c[k]["lines"] += len(w["test"])
        c[k]["wrong"] += bool(w.get("claims_works")) and not w["passes_final"]
        c[k]["judge_wrong"] += bool(w["judge"] and w["judge"]["works"] and not w["passes_final"])
        c[k]["cost"] += w["cost_usd"]
        c[k]["out"] += w["tokens"]["output"]
        for t_ in w["turns"]:
            p = t_.get("problem") or ""
            for why, codes in REFUSED.items():
                c[k][why] += any(code in p for code in codes)
            c[k]["declined"] += DECLINED in p
    out = ["# 1l: the language with slides and numeric bounce, at 8 and 16 steps", "",
           "Generated by `python -m ladder.report_1l`; never edited by hand. Same briefs, model (GPT-6.1), seeds and "
           "hidden test as 1j. 1k fixed the language's positions; 1l adds slide joints and bounce as a number "
           "(typed/lang.py) and says so in the guide the authors read. \"Steps held\" counts hidden-test lines that "
           "held, a world that never built counting none. \"No world\" counts replies with no world in them (the "
           "author declined), and \"refused\" counts files sent back before running, over all tries.", "",
           "| Steps | Arm | Worlds | Built | Worked | Steps held | No world | Refused: position or name | "
           "Refused: start overlap | Wrong \"it works\" | Judge passed a broken world | Output tokens / world | Cost |",
           "|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for n in LEVELS:
        for r in rows:
            k = (n, r)
            m = c[k]["n"]
            out.append(f"| {n} | {r} | {m} | {c[k]['built']} | {c[k]['worked']} | {c[k]['held']} of {c[k]['lines']} | "
                       f"{c[k]['declined']} | {c[k]['position or name']} | {c[k]['start overlap']} | {c[k]['wrong']} | "
                       f"{c[k]['judge_wrong']} | {c[k]['out'] / m:,.0f} | ${c[k]['cost']:.2f} |")
    new = "language, slides and bounce (1l)"
    out += ["", "## 1l against the others, steps held", "", "| Steps | Against | 1l | Other | Ratio |", "|---|---|---|---|---|"]
    for n in LEVELS:
        f = c[(n, new)]
        for r in rows[:4]:
            o = c[(n, r)]
            out.append(f"| {n} | {r} | {f['held']} of {f['lines']} | {o['held']} of {o['lines']} | "
                       f"{(f['held'] / f['lines']) / (o['held'] / o['lines']):.2f}x |")
    built = {r: sum(c[(n, r)]["built"] for n in LEVELS) for r in rows}
    out += ["", f"Built, 8 and 16 steps together: 1l {built[new]} of 16, 1k {built[rows[3]]}, 1j language {built[rows[2]]}; "
            f"Fisher p, 1l against 1j language = {fisher(built[new], 16, built[rows[2]], 16):.2f}.", "",
            f"1l cost ${sum(w['cost_usd'] for w in ws if w['row'] == new):.2f} for the worlds."]
    text = "\n".join(out) + "\n"
    (d1l / "results.md").write_text(text)
    print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
