"""1k against 1j at 8 and 16 steps: the fixed language beside 1j's three arms. No model calls.

    python -m ladder.report_1k      # writes ladder/results_1k/results.md
"""

from __future__ import annotations

import collections
import glob
import json
from pathlib import Path

from ladder.settings import JUDGE, JUDGE_1K_DIR, JUDGE_DIR, RESULTS_1K_DIR, RUNS_1K_DIR, RUNS_DIR
from langrun.report import fisher

LEVELS = (8, 16)
REFUSED = {"position or name": ("I CAN'T READ THIS POSITION", "UNKNOWN PART", "UNKNOWN PIECE"),
           "start overlap": ("PARTS START INSIDE EACH OTHER",)}


def load(runs: Path, judges: Path, label: dict) -> list[dict]:
    jv = {json.loads(Path(f).read_text())["world"]: json.loads(Path(f).read_text())
          for f in glob.glob(str(judges / f"*__{JUDGE}.json"))}
    out = []
    for f in sorted(glob.glob(str(runs / "*" / "*" / "world.json"))):
        w = json.loads(Path(f).read_text())
        if w["steps"] in LEVELS and w["arm"] in label:
            out.append(w | {"row": label[w["arm"]], "judge": jv.get(w["world"])})
    return out


def main() -> int:
    ws = load(RUNS_DIR, JUDGE_DIR, {"blind": "blind XML (1j)", "xml": "XML + words (1j)", "language": "language (1j)"}) + \
        load(RUNS_1K_DIR, JUDGE_1K_DIR, {"language": "fixed language (1k)"})
    rows = ["blind XML (1j)", "XML + words (1j)", "language (1j)", "fixed language (1k)"]
    c = collections.defaultdict(collections.Counter)
    for w in ws:
        k = (w["steps"], w["row"])
        t = w.get("final_test") or {}
        c[k]["n"] += 1
        c[k]["built"] += bool(t)
        c[k]["worked"] += w["passes_final"]
        c[k]["held"] += sum(bool(v) for line, v in t.get("checks", {}).items() if line in w["test"])
        c[k]["lines"] += len(w["test"])
        c[k]["wrong"] += bool(w.get("claims_works")) and not w["passes_final"]
        c[k]["judge_wrong"] += bool(w["judge"] and w["judge"]["works"] and not w["passes_final"])
        c[k]["cost"] += w["cost_usd"]
        c[k]["out"] += w["tokens"]["output"]
        for t_ in w["turns"]:
            p = t_.get("problem") or ""
            for why, codes in REFUSED.items():
                c[k][why] += any(code in p for code in codes)
    out = ["# 1k: the fixed language at 8 and 16 steps, beside 1j", "",
           "Generated by `python -m ladder.report_1k`; never edited by hand. Same briefs, prompts, model (GPT-6.1), seeds "
           "and hidden test as 1j; 1k changes only the language's positions (typed/lang.py). \"Steps held\" counts "
           "hidden-test lines that held, a world that never built counting none. \"Refused\" counts files sent back "
           "before running, over all tries.", "",
           "| Steps | Arm | Worlds | Built | Worked | Steps held | Refused: position or name | Refused: start overlap | "
           "Wrong \"it works\" | Judge passed a broken world | Output tokens / world | Cost |",
           "|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for n in LEVELS:
        for r in rows:
            k = (n, r)
            m = c[k]["n"]
            out.append(f"| {n} | {r} | {m} | {c[k]['built']} | {c[k]['worked']} | {c[k]['held']} of {c[k]['lines']} | "
                       f"{c[k]['position or name']} | {c[k]['start overlap']} | {c[k]['wrong']} | {c[k]['judge_wrong']} | "
                       f"{c[k]['out'] / m:,.0f} | ${c[k]['cost']:.2f} |")
    out += ["", "## Fixed language against the others, steps held", "", "| Steps | Against | Fixed language | Other | Ratio |",
            "|---|---|---|---|---|"]
    for n in LEVELS:
        f = c[(n, "fixed language (1k)")]
        for r in rows[:3]:
            o = c[(n, r)]
            out.append(f"| {n} | {r} | {f['held']} of {f['lines']} | {o['held']} of {o['lines']} | "
                       f"{(f['held'] / f['lines']) / (o['held'] / o['lines']):.2f}x |")
    f8 = [c[(n, "fixed language (1k)")] for n in LEVELS]
    b8 = [c[(n, "blind XML (1j)")] for n in LEVELS]
    out += ["", f"Built, 8 and 16 steps together: fixed language {sum(x['built'] for x in f8)} of {sum(x['n'] for x in f8)}, "
            f"1j language {sum(c[(n, 'language (1j)')]['built'] for n in LEVELS)} of 16; Fisher p against 1j language = "
            f"{fisher(sum(x['built'] for x in f8), 16, sum(c[(n, 'language (1j)')]['built'] for n in LEVELS), 16):.2f}.",
            "", f"1k cost ${sum(w['cost_usd'] for w in ws if w['row'] == 'fixed language (1k)'):.2f} for the worlds."]
    text = "\n".join(out) + "\n"
    (RESULTS_1K_DIR / "results.md").write_text(text)
    print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
