"""1j's results by chain length and arm. No model calls.

    python -m ladder.report      # writes ladder/results/results.md
"""

from __future__ import annotations

import collections
import glob
import json
from pathlib import Path

from ladder.settings import ARMS, JUDGE, JUDGE_DIR, LEVELS, RESULTS_DIR, RUNS_DIR
from langrun.report import fisher


def main() -> int:
    ws = [json.loads(Path(f).read_text()) for f in sorted(glob.glob(str(RUNS_DIR / "*" / "*" / "world.json")))]
    jv = {}
    for f in glob.glob(str(JUDGE_DIR / f"*__{JUDGE}.json")):
        r = json.loads(Path(f).read_text())
        jv[r["world"]] = r
    c = collections.defaultdict(collections.Counter)
    lines = collections.defaultdict(lambda: [0, 0])
    for w in ws:
        k = (w["steps"], w["arm"])
        t = w.get("final_test") or {}
        c[k]["n"] += 1
        c[k]["built"] += bool(t)
        c[k]["worked"] += w["passes_final"]
        c[k]["first"] += w["passes_first"]
        c[k]["wrong"] += bool(w.get("claims_works")) and not w["passes_final"]
        j = jv.get(w["world"])
        c[k]["both_wrong"] += bool(w.get("claims_works")) and not w["passes_final"] and bool(j and j["works"])
        c[k]["cost"] += w["cost_usd"]
        c[k]["out"] += w["tokens"]["output"]
        c[k]["secs"] += w["seconds"]
        checks = t.get("checks", {})
        lines[k][0] += sum(bool(v) for line, v in checks.items() if line in w["test"])
        lines[k][1] += len(w["test"])
    out = ["# 1j: the complexity ladder", "", "Generated by `python -m ladder.report`; never edited by hand. GPT-6.1 "
           "writes every world; the hidden test is hundred/hidden.py (fixed reading). \"Steps held\" counts hidden-test "
           "lines that held, a world that never built counting none.", "",
           "| Steps | Arm | Worlds | Built | Worked | Worked first try | Steps held | Wrong \"it works\" | "
           "...also passed by the judge | Output tokens / world | Minutes / world | Cost |",
           "|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for n in LEVELS:
        for a in ARMS:
            k = (n, a)
            if not c[k]["n"]:
                continue
            m = c[k]["n"]
            out.append(f"| {n} | {a} | {m} | {c[k]['built']} | {c[k]['worked']} | {c[k]['first']} | "
                       f"{lines[k][0]} of {lines[k][1]} | {c[k]['wrong']} | {c[k]['both_wrong']} | "
                       f"{c[k]['out'] / m:,.0f} | {c[k]['secs'] / m / 60:.1f} | ${c[k]['cost']:.2f} |")
    out += ["", "## Language against blind XML, by length", "",
            "| Steps | Worked: language / blind | p | Steps held: language / blind | Ratio of steps held |", "|---|---|---|---|---|"]
    for n in LEVELS:
        L, B = c[(n, "language")], c[(n, "blind")]
        if not (L["n"] and B["n"]):
            continue
        hl, hb = lines[(n, "language")], lines[(n, "blind")]
        ratio = (hl[0] / hl[1]) / (hb[0] / hb[1]) if hb[0] else float("inf")
        out.append(f"| {n} | {L['worked']} of {L['n']} / {B['worked']} of {B['n']} | "
                   f"{fisher(L['worked'], L['n'], B['worked'], B['n']):.2f} | {hl[0]} of {hl[1]} / {hb[0]} of {hb[1]} | "
                   f"{ratio:.2f}x |")
    out += ["", f"Total: {len(ws)} worlds, ${sum(w['cost_usd'] for w in ws):.2f} for the worlds; judged: {len(jv)}."]
    text = "\n".join(out) + "\n"
    (RESULTS_DIR / "results.md").write_text(text)
    print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
