"""Build worlds/results/results.md from the world JSON. Never edit it by hand.

    python -m worlds.report
    python -m worlds.report --runs .dryrun/worlds/runs --out .dryrun/worlds     # against dry runs

Uses the latest run per world. A summary written after reading the tables goes in results/summary.md and is
copied in verbatim.
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path

from loop.models import MODELS
from worlds import budget
from worlds.settings import ARMS, BRIEFS, MAX_ROUNDS, RESULTS_DIR, RUNS_DIR


def load(runs_dir: Path) -> list[dict]:
    latest = {}
    for p in sorted(runs_dir.glob("*/*/world.json")):
        w = json.loads(p.read_text())
        latest[w["world"]] = w
    return list(latest.values())


def n_of(ws, key) -> str:
    vals = [w.get(key) for w in ws if w.get(key) is not None]
    return f"{sum(bool(v) for v in vals)} of {len(vals)}" if vals else "n/a"


def models(ws):
    return sorted({w["model"] for w in ws}, key=lambda m: list(MODELS).index(m))


def by_model_arm(ws) -> list[str]:
    lines = ["| Model | Readback | Loads | Works as first written | Works in the end | Model's last claim right | "
             "Rounds used | Minutes per world | Cost per world |", "|---|---|---|---|---|---|---|---|---|"]
    for m in models(ws):
        for a in ARMS:
            rs = [w for w in ws if w["model"] == m and w["arm"] == a]
            if not rs:
                continue
            lines.append(f"| {MODELS[m].label} | {a} | {n_of(rs, 'loads')} | {n_of(rs, 'passes_first')} | "
                         f"{n_of(rs, 'passes_final')} | {n_of(rs, 'claim_correct')} | "
                         f"{sum(w['rounds'] for w in rs) / len(rs):.1f} | {sum(w['seconds'] for w in rs) / len(rs) / 60:.1f} | "
                         f"${sum(w['cost_usd'] for w in rs) / len(rs):.3f} |")
    return lines


def by_brief(ws) -> list[str]:
    by = defaultdict(list)
    for w in ws:
        by[(w["model"], w["brief"], w["arm"])].append(w)
    lines = ["| Model | Brief | Readback | First written | In the end | Failing checks at the end |",
             "|---|---|---|---|---|---|"]
    for m in models(ws):
        for b in BRIEFS:
            for a in ARMS:
                rs = by.get((m, b, a), [])
                if not rs:
                    continue
                fails = sorted({k for w in rs for k, v in (w.get("final_checks") or {}).items() if not v})
                lines.append(f"| {MODELS[m].label} | {b} | {a} | {n_of(rs, 'passes_first')} | {n_of(rs, 'passes_final')} | "
                             f"{'; '.join(fails) or ('did not load' if not all(w['loads'] for w in rs) else '')} |")
    return lines


def embarrassment(ws) -> list[str]:
    out = []
    for m in models(ws):
        pic = [w for w in ws if w["model"] == m and w["arm"] == "picture"]
        briefs_working = sorted({w["brief"] for w in pic if w["passes_final"]})
        out.append(f"- {MODELS[m].label}, picture: worlds working within {MAX_ROUNDS} rounds for "
                   f"{len(briefs_working)} of {len(BRIEFS)} briefs ({', '.join(briefs_working) or 'none'}).")
        for b in ("stack", "catapult"):
            p = [w for w in ws if w["model"] == m and w["brief"] == b and w["arm"] == "picture"]
            t = [w for w in ws if w["model"] == m and w["brief"] == b and w["arm"] == "text"]
            if p and t:
                out.append(f"- {MODELS[m].label}, {b}: works in the end with the picture {n_of(p, 'passes_final')}, "
                           f"text only {n_of(t, 'passes_final')}.")
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--runs", type=Path, default=RUNS_DIR)
    ap.add_argument("--out", type=Path, default=RESULTS_DIR)
    args = ap.parse_args()
    ws = load(args.runs)
    s = budget.spent()
    md = ["# Experiment 1c results: five worlds", "",
          f"Generated by `python -m worlds.report` from the world JSON; never edited by hand. {len(ws)} worlds; "
          f"1c spend ${s['exp1c']:.2f}.", "",
          "## By model and readback", "", *by_model_arm(ws), "",
          "## Embarrassment tests", "", *(embarrassment(ws) or ["Not run yet."]), "",
          "## By brief", "", *by_brief(ws), ""]
    summary = args.out / "summary.md"
    if summary.exists():
        md += ["## Summary", "", summary.read_text().strip(), ""]
    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "results.md").write_text("\n".join(md))
    print(f"{len(ws)} worlds -> {args.out / 'results.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
