"""Build worlds/results/sensitivity.md: the catapult test under a second reading of "a bucket 3 m away".

    python -m worlds.sensitivity

The test written before any run measures the bucket's distance from where the ball starts. Several worlds put
the bucket about 3 m from the catapult instead, with the ball resting on an arm behind it. This re-runs each
catapult world's last file and measures from the centre of the catapult's geoms (the `catapult` prefix) at the
start. Every other check is the pre-registered one. The pre-registered verdicts stay the result; this is a
sensitivity check, reported beside them. Never edit the output by hand.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

from worlds import tests
from worlds.settings import RESULTS_DIR, RUNS_DIR

DIST_CHECK = "bucket 3 m away (2.5 to 3.5 m)"


def latest_worlds(runs_dir: Path) -> list[tuple[Path, dict]]:
    latest = {}
    for path in sorted(runs_dir.glob("*catapult*/*/world.json")):  # timestamps sort, so the last one wins
        latest[path.parent.parent.name] = (path.parent, json.loads(path.read_text()))
    return [latest[k] for k in sorted(latest)]


def last_file(run_dir: Path, world: dict) -> tuple[str, Path] | None:
    loaded = [f for f in world["files"] if f.get("loaded")]
    if not loaded:
        return None
    label = loaded[-1]["label"]
    return label, run_dir / f"{label}.xml"


def from_catapult(xml: str) -> tuple[float, dict]:
    j = tests.judge("catapult", xml)
    r = j["run"]
    m = r.model
    cat = tests.geoms_named(m, "catapult")
    bucket = tests.geoms_of(m, tests.body(m, "bucket"))
    clo, chi = tests.aabb(r, cat, 0)
    blo, bhi = tests.aabb(r, bucket, 0)
    d = float(np.hypot(*((blo[:2] + bhi[:2]) / 2 - (clo[:2] + chi[:2]) / 2)))
    return d, j


def main() -> int:
    rows = ["| World | Last file | Distance from ball start (m) | From catapult (m) | Pre-registered | "
            "Measured from catapult | Other failing checks |", "|---|---|---|---|---|---|---|"]
    n_pre = n_alt = 0
    for run_dir, w in latest_worlds(RUNS_DIR):
        lf = last_file(run_dir, w)
        if lf is None:
            continue
        label, path = lf
        d_cat, j = from_catapult(path.read_text())
        checks = dict(j["checks"])
        others = [k for k, v in checks.items() if not v and k != DIST_CHECK]
        pre = j["passed"]
        alt = not others and 2.5 <= d_cat <= 3.5 and not j.get("diverged")
        n_pre += pre
        n_alt += alt
        rows.append(f"| {w['world']} | {label} | {j['values']['distance_m']:.3f} | {d_cat:.3f} | "
                    f"{'works' if pre else 'fails'} | {'works' if alt else 'fails'} | {'; '.join(others)} |")
    md = ["# Experiment 1c: the catapult under a second reading of \"3 m away\"", "",
          "Generated by `python -m worlds.sensitivity`; never edited by hand. The pre-registered test measures "
          "the bucket from where the ball starts; this measures it from the centre of the catapult's geoms. "
          "Every other check is unchanged. The pre-registered verdicts are the result.", "",
          f"Catapult worlds working in the end: {n_pre} pre-registered, {n_alt} measured from the catapult.", "",
          *rows, ""]
    (RESULTS_DIR / "sensitivity.md").write_text("\n".join(md))
    print(f"{n_pre} vs {n_alt} -> {RESULTS_DIR / 'sensitivity.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
